#!/usr/bin/bash

#Get the first three octet of the network IP
ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3 | uniq > octets.txt

#Set variable to have the value of octets.txt
OCTETS=$(cat octets.txt)

#Create a new .txt file
echo "" > $OCTETS.txt

#Loop
for ip in {1..254}
do
	ping -c 1 $OCTETS.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $OCTETS.txt &
done

 

cat $OCTETS.txt | sort > Sorted_$OCTETS.txt

#Perform scan
nmap -sS -iL Sorted_$OCTETS.txt 

exit
 
